#!/bin/bash

function indent {
  echo ":: $*"
}

dir=$(readlink -f $(dirname $0))
wallpaper_dir=${wallpaper_dir:-$0/backgrounds/}

if [ 0 = $# ]; then
  indent "No file argument provided"
  exit 1
fi

for file in $*; do
  if [ ! -f $file ]; then
    indent "File '$file' doesn't exits"
    exit 1
  fi
done

cp $* $wallpaper_dir
cd $wallpaper_dir
$dir/detect_color $*
