#!/bin/bash
wallpaper_dir=~/.config/herbstluftwm/backgrounds/
dir=$(readlink -f $(dirname $0))

if [ 0 = $# ]; then
  echo "No file argument provided"
  exit 1
fi

for file in $*; do
  if [ ! -f $file ]; then
    echo "File '$file' doesn't exits"
    exit 1
  fi
done

cp $* $wallpaper_dir
cd $wallpaper_dir
$dir/detect_color $*
