#!/bin/bash

dir=${dir:-$(readlink -f $(dirname $0))}
wallpaper_dir=${wallpaper_dir:-$dir/backgrounds/}

source $dir/functions

background=$(find $wallpaper_dir -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z | xargs -0)
filename=$(basename $background)
dirname=$(dirname $background)

feh --bg-scale $background
indent "Background set to $background"

ln -f $dirname/.$filename.colors ~/.colors
xrdb $dirname/.$filename.Xres
#xrdb ./solarized.Xres
