#!/bin/bash

dir=${dir:-$(readlink -f $(dirname $0))}
wallpaper_dir=${wallpaper_dir:-$dir/backgrounds/}

source $dir/functions

if [ -z $1 ]; then
  background=$(find $wallpaper_dir -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z | xargs -0)
else
  background=$wallpaper_dir/$1

  if [ ! -f $background ]; then
    indent "$1 does not exist in $wallpaper_dir"
    exit 1
  fi
fi

filename=$(basename $background)
dirname=$(dirname $background)

feh --bg-scale $background

if [ $? -ne 0 ]; then
  indent "Failed to set $background as background"
else
  indent "Set $background as background"

  ln -f $dirname/.$filename.colors ~/.colors
  xrdb $dirname/.$filename.Xres
  #xrdb ./solarized.Xres
fi
