#!/bin/bash

function main {

  # Snippet from SO user Dave Dopson http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
  SOURCE="${BASH_SOURCE[0]}"
  # resolve $SOURCE until the file is no longer a symlink
  while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    # if $SOURCE was a relative symlink, we need to resolve it
    # relative to the path where the symlink file was located
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

  WALLPAPER_DIR=${WALLPAPER_DIR:-~/.wallpapers/}

  # if [ ! -e WALLPAPER_DIR ]; then
  #   if [ ! -d WALLPAPER_DIR ]; then
  #     indent "ERROR: must create wallpaper directory. "
  #     exit 1
  #   fi
  # fi


  prog=$1
  shift

  case $prog in
    "usage" | "-h" | "--help")
      usage
      ;;
    "update")
      update
      ;;
    "add")
      add $*
      ;;
    "rm" | "remove")
      remove $*
      ;;
    "change")
      change $*
      ;;
    "current")
      current $*
      ;;
    "ls" | "list")
      list $*
      ;;
    "colors")
      colors
      ;;
    *)
      indent "$prog is not a recognised directive"
      ;;
  esac
}

#:: Prety print function
function indent {
  echo ":: $*"
}

#:: Directives

function update {
  for f in ~/.wallpapers/*
  do
    mv $f $(echo $f | sed 's/ //g') >/dev/null 2>&1
  done;

  set -- $(ls ~/.wallpapers/*)

  add $*
}

function add {


  if [ 0 = $# ]; then
    indent "No file argument provided"
    exit 1
  fi

  files=$*

  for file in $files; do
    if [ ! -f $file ]; then
      indent "File '$file' doesn't exits"
      exit 1
    fi
  done

  cp $files $WALLPAPER_DIR >/dev/null 2>&1
  cd $WALLPAPER_DIR

  for file in $*; do
    echo ":: Generating .$file.colors and .$file.Xres in $PWD"
    python2 $DIR/py/color_detect.py $file
  done
}

function remove {
  if [ 0 = $# ]; then
    indent "No file argument provided"
    exit 1
  fi

  for file in $*; do
    indent "Removing $file"
    rm ${WALLPAPER_DIR}/${file}
    rm ${WALLPAPER_DIR}/.${file}.{colors,Xres}
  done
}

function change {
  #:: Select a random background from WALLPAPER_DIR, or use the passed background
  if [ -z $1 ]; then
    background=$(find $WALLPAPER_DIR -type f \( -name '*.jpg' -o -name '*.png' \) | shuf -n1)
  else
    background=$WALLPAPER_DIR/$1

    if [ ! -f $background ]; then
      indent "$1 does not exist in $WALLPAPER_DIR"
      exit 1
    fi
  fi

  if [ -f ${background}.Xres ] || [ -f ${background}.colors ]; then
    indent "Could not find ${background}.Xres or ${background}.colors"
    exit 1
  fi

  filename=$(basename $background)
  dirname=$(dirname $background)

  command -v gsettings >/dev/null 2>&1

  #:: Set the background
  if [ $? ]; then
    gsettings set org.gnome.desktop.background picture-uri "file://$background"
  else
    feh --bg-fill $background
  fi

  #:: Record the current background
  ln -sf $background  $WALLPAPER_DIR/.current

  if [ $? -ne 0 ]; then
    indent "Failed to set $background as background"
  else
    indent "Set $background as background"

    #:: Set the colorscheme
    ln -f ${dirname}/.${filename}.colors ~/.colors
    ln -f ${dirname}/.${filename}.gnome ~/.gnomecolors

    command -v gconftool-2 >/dev/null 2>&1
    
    if [ $? ]; then
      gconftool-2 --set /apps/gnome-terminal/profiles/Default/palette --type string \"$(cat ~/.gnomecolors)\"
    fi

    xrdb ${dirname}/.${filename}.Xres
  fi
}

function current {
  indent $(readlink -f $WALLPAPER_DIR/.current)
}

function list {
  ls $* $WALLPAPER_DIR
}

function colors {
  # Original: http://frexx.de/xterm-256-notes/
  #           http://frexx.de/xterm-256-notes/data/colortable16.sh
  # Modified by Aaron Griffin
  # and further by Kazuo Teramoto
  FGNAMES=(' black ' '  red  ' ' green ' ' yellow' '  blue ' 'magenta' '  cyan ' ' white ')
  BGNAMES=('DFT' 'BLK' 'RED' 'GRN' 'YEL' 'BLU' 'MAG' 'CYN' 'WHT')

  echo "     ┌──────────────────────────────────────────────────────────────────────────┐"
  for b in {0..8}; do
    ((b>0)) && bg=$((b+39))

    echo -en "\033[0m ${BGNAMES[b]} │ "
    
    for f in {0..7}; do
      echo -en "\033[${bg}m\033[$((f+30))m ${FGNAMES[f]} "
    done
    
    echo -en "\033[0m │"
    echo -en "\033[0m\n\033[0m     │ "
    
    for f in {0..7}; do
      echo -en "\033[${bg}m\033[1;$((f+30))m ${FGNAMES[f]} "
    done

    echo -en "\033[0m │"
    echo -e "\033[0m"

    ((b<8)) &&
    echo "     ├──────────────────────────────────────────────────────────────────────────┤"
  done
  echo "     └──────────────────────────────────────────────────────────────────────────┘"
}

function usage {
  printf "%b" "  $0 [action] [options]

Actions
- usage:         Print this help massage.
- add [file]...: Add file, or files, to wallpaper database.
- rm  [file]...: Remove file, or files, from wallpaper database.
- change [file]: Set the wallpaper to file, or a random wallpaper
                 from the wallpaper database.
- current:       List the current background
- ls:            List all wallpapers in the database.
- colors:        Display the current set of colors.
- update:        Add any files in the $WALLPAPER_DIR directory. 
"
}

#:: End function declaration, begin executing
main $*
