#!/bin/bash

function main {

  # Snippet from SO user Dave Dopson http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
  SOURCE="${BASH_SOURCE[0]}"
  # resolve $SOURCE until the file is no longer a symlink
  while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    # if $SOURCE was a relative symlink, we need to resolve it
    # relative to the path where the symlink file was located
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

  WALLPAPER_DIR=${WALLPAPER_DIR:-~/.wallpapers/}

  if [ ! -e $WALLPAPER_DIR ]; then
    mkdir $WALLPAPER_DIR
  fi

  prog=$1
  shift

  gnome=false
  declare -a files

  while [ $# -gt 0 ] ; do
          case "$1" in
                  --gnome) gnome=true ; shift;;
                  --) shift ;;
                  -*) echo "bad option '$1'" ; exit 1 ;;
                  *) files=("${files[@]}" "$1") ; shift ;;
           esac
  done

  case $prog in
    "usage" | "-h" | "--help")
      usage
      ;;
    "update")
      update
      ;;
    "add")
      add $files
      ;;
    "rm" | "remove")
      remove $files
      ;;
    "change")
      change $files
      ;;
    "current")
      current $files
      ;;
    "ls" | "list")
      list $files
      ;;
    "colors")
      colors
      ;;
    *)
      indent "$prog is not a recognised directive"
      ;;
  esac
}

#:: Prety print function
function indent {
  echo ":: $*"
}

#:: Directives

function update {
  for f in $WALLPAPER_DIR
  do
    mv $f $(echo $f | sed 's/ //g') >/dev/null 2>&1
  done;

  set -- $(ls $WALLPAPER_DIR/*)

  add $*
}

function add {
  if [ 0 = $# ]; then
    indent "No file argument provided"
    exit 1
  fi

  cp $* $WALLPAPER_DIR >/dev/null 2>&1
  cd $WALLPAPER_DIR

  for file in $*; do
    # The files in $* are full pathnames, appending `.` to the front
    # generates `./home/<user>/file`, not `.file`
    # This gets the basename
    file=$(dirname $file)/$(basename $file)
    if [ ! -e .$file.colors ]; then
      if [ ! -e .$file.Xres ]; then
        if [ ! -e .$file.gnome ]; then
          indent "Generating color schemes for $file in $WALLPAPER_DIR"
          python2 $DIR/py/color_detect.py $file
        fi
      fi
    fi
  done
}

function remove {
  if [ 0 = $# ]; then
    indent "No file argument provided"
    exit 1
  fi

  for file in $*; do
    indent "Removing $file"
    rm ${WALLPAPER_DIR}/${file}
    rm ${WALLPAPER_DIR}/.${file}.{colors,Xres}
  done
}

function change {
  #:: Select a random background from WALLPAPER_DIR, or use the passed background
  if [ -z $1 ]; then
    background=$(find $WALLPAPER_DIR -type f \( -name '*.jpg' -o -name '*.png' \) | shuf -n1)
  else
    background=$WALLPAPER_DIR/$1

    if [ ! -f $background ]; then
      indent "$1 does not exist in $WALLPAPER_DIR"
      exit 1
    fi
  fi

  if [ -f ${background}.Xres ] || [ -f ${background}.colors ]; then
    indent "Could not find ${background}.Xres or ${background}.colors"
    exit 1
  fi

  filename=$(basename $background)
  dirname=$(dirname $background)

  #:: Set the background
  if $gnome; then
    gsettings set org.gnome.desktop.background picture-uri "file://$background"
  else
    feh --bg-fill $background
  fi

  #:: Record the current background
  ln -sf $background  $WALLPAPER_DIR/.current

  if [ $? -ne 0 ]; then
    indent "Failed to set $background as background"
  else
    indent "Set $background as background"

    #:: Set the colorscheme
    ln -f ${dirname}/.${filename}.colors ~/.colors
    if $gnome; then
      ln -f ${dirname}/.${filename}.gnome ~/.gnomecolors
      gconftool-2 --set /apps/gnome-terminal/profiles/Default/palette --type string \"$(cat ~/.gnomecolors)\"
    fi

    xrdb ${dirname}/.${filename}.Xres
  fi
}

function current {
  indent $(readlink -f $WALLPAPER_DIR/.current)
}

function list {
  ls $* $WALLPAPER_DIR
}

function colors {
  # Original: http://frexx.de/xterm-256-notes/
  #           http://frexx.de/xterm-256-notes/data/colortable16.sh
  # Modified by Aaron Griffin
  # and further by Kazuo Teramoto
  FGNAMES=(' black ' '  red  ' ' green ' ' yellow' '  blue ' 'magenta' '  cyan ' ' white ')
  BGNAMES=('DFT' 'BLK' 'RED' 'GRN' 'YEL' 'BLU' 'MAG' 'CYN' 'WHT')

  echo "     ┌──────────────────────────────────────────────────────────────────────────┐"
  for b in {0..8}; do
    ((b>0)) && bg=$((b+39))

    echo -en "\033[0m ${BGNAMES[b]} │ "
    
    for f in {0..7}; do
      echo -en "\033[${bg}m\033[$((f+30))m ${FGNAMES[f]} "
    done
    
    echo -en "\033[0m │"
    echo -en "\033[0m\n\033[0m     │ "
    
    for f in {0..7}; do
      echo -en "\033[${bg}m\033[1;$((f+30))m ${FGNAMES[f]} "
    done

    echo -en "\033[0m │"
    echo -e "\033[0m"

    ((b<8)) &&
    echo "     ├──────────────────────────────────────────────────────────────────────────┤"
  done
  echo "     └──────────────────────────────────────────────────────────────────────────┘"
}

function usage {
  printf "%b" "  $0 [action] [options]

Actions
- usage:         Print this help massage.
- add [file]...: Add file, or files, to wallpaper database.
- rm  [file]...: Remove file, or files, from wallpaper database.
- change [file]: Set the wallpaper to file, or a random wallpaper
                 from the wallpaper database.
- current:       List the current background
- ls:            List all wallpapers in the database.
- colors:        Display the current set of colors.
- update:        Add any files in the $WALLPAPER_DIR directory. 
"
}

#:: End function declaration, begin executing
main $*
