#!/bin/bash

dir=$(readlink -f $(dirname $0))


if [ 0 = $# ]; then
  echo "No file argument provided"
  exit 1
fi

for file in $*; do
  if [ ! -f $file ]; then
    echo "File '$file' doesn't exits"
    exit 1
  fi
done

for file in $*; do
  echo ":: Generating .$file.colors and .$file.Xres in $PWD"
  python2 $dir/py/color_detect.py $file
done

echo "done"
exit 0
